class language:

    def __init__(self):
        pass

    def zh_CN(self):
        self.title = '抽卡模拟器'
        self.onewish = '单抽'
        self.tenwish = '十连'
        self.settings = '设置'
        self.choosedb = '选择数据库'
        self.deletedb = '删除数据库'
        self.newdb = '新建数据库'
        self.save = '保存'
        self.savedb = '保存数据库'
        self.deletedbmsg = '你确定要删除该数据库吗？'
        self.cancel = '取消'
        self.delete = '删除'
        self.new = '新建'
        self.ok = '确定'
        self.rename = '重命名'
        self.about = '关于'
        self.chooselang = '选择语言'
        self.chooselangmsg = '选择语言后需要重启应用程序后才能生效，是否继续？'
        self.item = '项'
        self.newitem = '新建项'
        self.deleteitem = '删除项'
        self.deleteitemmsg = '你确定要删除该项吗？'
        self.easteregg = '彩蛋'
        self.eastereggmsg = '恭喜你发现了彩蛋( *^▽^* )'
        self.setname = '设置名称：'
        self.setitemdata = '修改抽卡物品数据'
        self.sddl = '说的道理'
        self.wow = '袜袄！！！'
        self.smg = '小保底  '
        self.bmg = '大保底'
        self.option = '提示'
        self.optionmsg = '必须保留至少一项！'
        self.probability = '概率：'
        self.res = '物品'
        self.aboutmsg = '作者：smb-studio\nGithub项目：myphone12/ck_redefined\n欢迎star该项目或给该项目提issues哦！！_(:з」∠)_'

    def en_US(self):
        self.title = 'Wish stimulator'
        self.onewish = 'One wish'
        self.tenwish = 'Ten wish'
        self.settings = 'Settings'
        self.choosedb = 'Choose Database'
        self.deletedb = 'Delete Database'
        self.newdb = 'New Database'
        self.deletedbmsg = 're you sure you want to delete this database?'
        self.save = 'Save'
        self.savedb = 'Save Database'
        self.cancel = 'Cancel'
        self.delete = 'Delete'
        self.new = 'New'
        self.ok = 'OK'
        self.rename = 'Rename'
        self.about = 'About'
        self.chooselang = 'Choose Language'
        self.chooselangmsg = 'After selecting the language, the application needs to be restarted for it to take effect. Do you want to continue?'
        self.item = 'Item'
        self.newitem = 'New Item'
        self.deleteitem = 'Delete Item'
        self.deleteitemmsg = 'Are you sure you want to delete this item?'
        self.easteregg = 'EasterEgg'
        self.eastereggmsg = 'Congratulations! You have discovered an Easter egg!:P'
        self.setname = 'Set name:'
        self.setitemdata = 'Modify the data of items'
        self.sddl = 'What I said is reasonable'
        self.smg = 'Small minimum guarantee'
        self.bmg = 'Big minimum guarantee'
        self.wow = 'WOW!!!'
        self.option = 'Option'
        self.optionmsg = 'At least one item must be retained!'
        self.probability = 'probability:'
        self.res = 'resources'
        self.aboutmsg = 'author: smb-studio\nGithub repositories: myphone12/ck_redefined\nWelcome to star this project or raise issues for it!! _(:з」∠)_'