class lang:
    def __init__(self):
        pass

class language:

    def __init__(self):
        self.lang = lang

    def zh_CN(self):
        self.lang.title = '抽卡模拟器'
        self.lang.onewish = '单抽'
        self.lang.tenwish = '十连'
        self.lang.settings = '设置'
        self.lang.choosedb = '选择数据库'
        self.lang.deletedb = '删除数据库'
        self.lang.newdb = '新建数据库'
        self.lang.save = '保存'
        self.lang.savedb = '保存数据库'
        self.lang.deletedbmsg = '你确定要删除该数据库吗？'
        self.lang.cancel = '取消'
        self.lang.delete = '删除'
        self.lang.new = '新建'
        self.lang.ok = '确定'
        self.lang.rename = '重命名'
        self.lang.about = '关于'
        self.lang.chooselang = '选择语言'
        self.lang.chooselangmsg = '选择语言后需要重启应用程序后才能生效，是否继续？'
        self.lang.item = '项'
        self.lang.newitem = '新建项'
        self.lang.deleteitem = '删除项'
        self.lang.deleteitemmsg = '你确定要删除该项吗？'
        self.lang.easteregg = '彩蛋'
        self.lang.eastereggmsg = '恭喜你发现了彩蛋( *^▽^* )'
        self.lang.setname = '设置名称：'
        self.lang.setitemdata = '修改抽卡物品数据'
        self.lang.sddl = '说的道理'
        self.lang.wow = '袜袄！！！'

    def en_US(self):
        self.lang.title = 'Wish stimulator'
        self.lang.onewish = 'One wish'
        self.lang.tenwish = 'Ten wish'
        self.lang.settings = 'Settings'
        self.lang.choosedb = 'Choose Database'
        self.lang.deletedb = 'Delete Database'
        self.lang.newdb = 'New Database'
        self.lang.deletedbmsg = 're you sure you want to delete this database?'
        self.lang.save = 'Save'
        self.lang.savedb = 'Save Database'
        self.lang.cancel = 'Cancel'
        self.lang.delete = 'Delete'
        self.lang.new = 'New'
        self.lang.ok = 'OK'
        self.lang.rename = 'Rename'
        self.lang.about = 'About'
        self.lang.chooselang = 'Choose Language'
        self.lang.chooselangmsg = 'After selecting the language, the application needs to be restarted for it to take effect. Do you want to continue?'
        self.lang.item = 'Item'
        self.lang.newitem = 'New Item'
        self.lang.deleteitem = 'Delete Item'
        self.lang.deleteitemmsg = 'Are you sure you want to delete this item?'
        self.lang.easteregg = 'EasterEgg'
        self.lang.eastereggmsg = 'Congratulations! You have discovered an Easter egg!:P'
        self.lang.setname = 'Set name:'
        self.lang.setitemdata = 'Modify the data of items'
        self.lang.sddl = 'What I said is reasonable'
        self.lang.wow = 'WOW!!!'